# Generated by Django 6.1.1 on 2026-10-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_booking_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_reference',
            field=models.CharField(default='F69287EF', max_length=8, unique=True),
        ),
    ]
